/** @externs */
/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from packages/router/src/utils/preactivation.closure.js:

/** @typedef {?} */
var Checks;
// externs from packages/router/src/operators/prioritized_guard_value.closure.js:

/** @typedef {?} */
var INTERIM_VALUES;
