/** @externs */
/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from /b/f/w/packages/router/src/utils/preactivation.ts:
/** @const */
var angular$packages$router$src$utils$preactivation = {};

/** @typedef {?} */
angular$packages$router$src$utils$preactivation.Checks;
// externs from /b/f/w/packages/router/src/operators/prioritized_guard_value.ts:
/** @const */
var angular$packages$router$src$operators$prioritized_guard_value = {};

/** @typedef {?} */
var INTERIM_VALUES;
