/** @externs */
/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from /home/circleci/.cache/bazel/_bazel_circleci/9ce5c2144ecf75d11717c0aa41e45a8d/execroot/angular/packages/router/src/utils/preactivation.ts:
/** @const */
var angular$packages$router$src$utils$preactivation = {};

/** @typedef {?} */
angular$packages$router$src$utils$preactivation.Checks;
// externs from /home/circleci/.cache/bazel/_bazel_circleci/9ce5c2144ecf75d11717c0aa41e45a8d/execroot/angular/packages/router/src/operators/prioritized_guard_value.ts:
/** @const */
var angular$packages$router$src$operators$prioritized_guard_value = {};

/** @typedef {?} */
var INTERIM_VALUES;
